cloud.aws.credentials.accessKey:
cloud.aws.credentials.secretKey: 
cloud.aws.credentials.instanceProfile: false
cloud.aws.region.static: us-east-1

sns.topic: demo1

localstack:
  sns:
    url: http://localhost:4575
  sqs:
    url: http://localhost:4576
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .html
---

spring.profiles: prod
cloud.aws.credentials.instanceProfile: true